name: Deploy to Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PRODUCTION }}
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:  
            approve_release:
                description: "Approve release to production"
                required: true
                default: "no"
                type: choice
                options:
                    - yes
                    - no

jobs:

  Approve:
        name: Approve the release
        runs-on: ubuntu-latest
        steps:
            - name: Check approval status
              run: |
               if ["${{github.event.inputs.approve_release }}" != "yes" ]; then echo "Release not approved.."
               exit 1
               fi
               echo " Release approved. Proceeding to deployment" 

            - name: Deploy release
              run: echo "Deploying release to production"

  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}