name: Continuous Integration
on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
                cache: 'npm' # cache the node modules  
            
            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Run typescript
              run: npm i -g typescript && tsc

            - name: Run jest tests
              run: npm run test

            - name: Run eslint
              run: npm run lint && eslint

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: sylvaincodes/youtube_orion_admin  
            
    
          

           


            
            

            